# Multi-Model Customer Support Evaluation

This notebook compares four selected instruction-tuned language models on the same customer support dataset:

- Microsoft Phi-3 Mini, 3.8B
- Google Gemma-2-2B-IT, 2B
- Mistral-7B-Instruct-v0.3, 7B
- Qwen2.5-7B-Instruct, 7B

Each model is loaded, evaluated, then unloaded before the next model is loaded. This avoids keeping all models in GPU memory at once.

In [1]:
!pip -q install -U "transformers>=4.45.0" accelerate sentencepiece pandas bert-score rouge-score nltk psutil

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 8.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 149.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 151.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 89.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 19.4 MB/s eta 0:00:00
  Building wheel for rouge-score (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.

In [2]:
import gc
import time
from pathlib import Path

import pandas as pd
import torch
import psutil

from transformers import AutoTokenizer, AutoModelForCausalLM

## Runtime Check

Use a GPU runtime. The 7B models need much more memory than Phi-3 and Gemma.

In [3]:
if not torch.cuda.is_available():
    raise RuntimeError("GPU is not available. In Colab, go to Runtime > Change runtime type > GPU.")

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print("BF16 supported:", torch.cuda.is_bf16_supported())

CUDA available: True
GPU: NVIDIA A100-SXM4-80GB
BF16 supported: True

## Optional Hugging Face Login

Gemma requires accepting Google's license on Hugging Face before download. If Gemma fails with an access or gated-repo error, log in here, accept the model conditions on Hugging Face, restart the runtime, and run again.

Clear the output of this cell before submission.

In [4]:
# Only run this if Hugging Face asks you to log in or Gemma gives an access error.
# from huggingface_hub import login
# login()

In [5]:
import os
from huggingface_hub import login
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

if HF_TOKEN is None:
    raise ValueError("HF_TOKEN not found. Add it in Colab Secrets first.")

login(token=HF_TOKEN)
os.environ["HF_TOKEN"] = HF_TOKEN

print("Hugging Face token loaded successfully.")

Hugging Face token loaded successfully.

## Load Dataset

The dataset must include: `ID`, `Category`, `Difficulty`, `Customer Prompt`, and `Reference Answer`.

In [6]:
DATASET_URL = "https://raw.githubusercontent.com/hafishafi/customer-support-Dataset/main/dataset.csv"

dataset = pd.read_csv(DATASET_URL)

print("Rows:", len(dataset))
display(dataset.head())

Rows: 100

,ID,Category,Difficulty,Customer Prompt,Reference Answer
0,1,Account Management,Easy,I forgot my password. How can I reset it?,"Click the ""Forgot Password"" option on the logi..."
1,2,Account Management,Easy,I can't log into my account.,Verify your email and password are correct. If...
2,3,Account Management,Easy,My account is locked. What should I do?,Wait for the lock period to expire or contact ...
3,4,Account Management,Easy,How do I change my email address?,"Go to your account settings, update your email..."
4,5,Account Management,Medium,"I changed my email yesterday, and now I can't ...",Try logging in with your new email address. If...

In [7]:
import pandas as pd

DATASET_URL = "https://raw.githubusercontent.com/hafishafi/customer-support-Dataset/main/dataset.csv"

dataset = pd.read_csv(DATASET_URL)

required_columns = ["ID", "Category", "Difficulty", "Customer Prompt", "Reference Answer"]
missing_columns = [col for col in required_columns if col not in dataset.columns]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

print("Rows:", len(dataset))
display(dataset.head())

Rows: 100

,ID,Category,Difficulty,Customer Prompt,Reference Answer
0,1,Account Management,Easy,I forgot my password. How can I reset it?,"Click the ""Forgot Password"" option on the logi..."
1,2,Account Management,Easy,I can't log into my account.,Verify your email and password are correct. If...
2,3,Account Management,Easy,My account is locked. What should I do?,Wait for the lock period to expire or contact ...
3,4,Account Management,Easy,How do I change my email address?,"Go to your account settings, update your email..."
4,5,Account Management,Medium,"I changed my email yesterday, and now I can't ...",Try logging in with your new email address. If...

## Select Models

For a quick test, set `EVALUATION_LIMIT = 3` or `5`. For final results, keep it as `None` so all 100 prompts are evaluated.

In [8]:
SELECTED_MODELS = [
    {
        "label": "Microsoft Phi-3 Mini",
        "model_id": "microsoft/Phi-3-mini-4k-instruct",
        "size": "3.8B",
        "developer": "Microsoft",
        "dtype": "float16",
        "attn_implementation": "eager"
    },
    {
        "label": "Google Gemma-2-2B-IT",
        "model_id": "google/gemma-2-2b-it",
        "size": "2B",
        "developer": "Google",
        "dtype": "bfloat16",
        "attn_implementation": "eager"
    },
    {
        "label": "Mistral-7B-Instruct-v0.3",
        "model_id": "mistralai/Mistral-7B-Instruct-v0.3",
        "size": "7B",
        "developer": "Mistral AI",
        "dtype": "float16",
        "attn_implementation": "eager"
    },
    {
        "label": "Qwen2.5-7B-Instruct",
        "model_id": "Qwen/Qwen2.5-7B-Instruct",
        "size": "7B",
        "developer": "Alibaba Cloud",
        "dtype": "bfloat16",
        "attn_implementation": "eager"
    }
]

EVALUATION_LIMIT = None  # Change to 5 for a quick test, then back to None for final results.
MAX_NEW_TOKENS = 150

test_dataset = dataset.head(EVALUATION_LIMIT).copy() if EVALUATION_LIMIT else dataset.copy()

print("Models:", len(SELECTED_MODELS))
print("Prompts per model:", len(test_dataset))
print("Total generations:", len(SELECTED_MODELS) * len(test_dataset))

Models: 4
Prompts per model: 100
Total generations: 400

## Helper Functions

In [9]:
def resolve_dtype(dtype_name):
    if dtype_name == "bfloat16" and torch.cuda.is_bf16_supported():
        return torch.bfloat16
    return torch.float16


def load_selected_model(model_info):
    model_id = model_info["model_id"]
    dtype = resolve_dtype(model_info.get("dtype", "float16"))

    print(f"\nLoading {model_info['label']} ({model_id})...")

    tokenizer = AutoTokenizer.from_pretrained(model_id)

    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token

    load_kwargs = {
        "torch_dtype": dtype,
        "device_map": "auto"
    }

    attn_implementation = model_info.get("attn_implementation")
    if attn_implementation:
        load_kwargs["attn_implementation"] = attn_implementation

    try:
        model = AutoModelForCausalLM.from_pretrained(model_id, **load_kwargs)
    except TypeError:
        load_kwargs.pop("attn_implementation", None)
        model = AutoModelForCausalLM.from_pretrained(model_id, **load_kwargs)

    model.eval()
    print("Loaded:", model.config.name_or_path)
    return tokenizer, model


def unload_selected_model(model=None, tokenizer=None):
    if model is not None:
        del model
    if tokenizer is not None:
        del tokenizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()


def build_messages(customer_prompt):
    instruction = (
        "You are a helpful customer support assistant. "
        "Answer the customer's question clearly, accurately, and concisely."
    )

    return [
        {
            "role": "user",
            "content": f"{instruction}\n\nCustomer question:\n{customer_prompt}"
        }
    ]


def generate_response(prompt, model, tokenizer, max_new_tokens=150):
    messages = build_messages(str(prompt))

    try:
        inputs = tokenizer.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_tensors="pt",
            return_dict=True
        ).to(model.device)
    except TypeError:
        formatted_prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        inputs = tokenizer(formatted_prompt, return_tensors="pt").to(model.device)

    input_token_count = inputs["input_ids"].shape[-1]

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()

    start_time = time.perf_counter()

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    latency = time.perf_counter() - start_time

    generated_ids = outputs[0][input_token_count:]
    response = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    generated_tokens = int(generated_ids.numel())
    response_length = len(response.split())
    tokens_per_second = generated_tokens / latency if latency > 0 else 0

    gpu_peak_memory_gb = (
        torch.cuda.max_memory_allocated() / (1024 ** 3)
        if torch.cuda.is_available()
        else 0
    )

    cpu_process_memory_gb = psutil.Process().memory_info().rss / (1024 ** 3)

    return {
        "Response": response,
        "Latency": latency,
        "Generated Tokens": generated_tokens,
        "Response Length": response_length,
        "Tokens/sec": tokens_per_second,
        "GPU Peak Memory GB": gpu_peak_memory_gb,
        "CPU Process Memory GB": cpu_process_memory_gb
    }

## Run All Models

This is the longest cell. It loads one model, runs all prompts, unloads the model, then moves to the next model.

In [10]:
all_results = []

for model_info in SELECTED_MODELS:
    tokenizer = None
    model = None

    try:
        tokenizer, model = load_selected_model(model_info)

        for _, row in test_dataset.iterrows():
            generated = generate_response(
                row["Customer Prompt"],
                model,
                tokenizer,
                max_new_tokens=MAX_NEW_TOKENS
            )

            all_results.append({
                "Model Label": model_info["label"],
                "Model ID": model_info["model_id"],
                "Model Size": model_info["size"],
                "Developer": model_info["developer"],
                "ID": row["ID"],
                "Category": row["Category"],
                "Difficulty": row["Difficulty"],
                "Prompt": row["Customer Prompt"],
                "Reference Answer": row["Reference Answer"],
                **generated
            })

            print(f"{model_info['label']} - completed prompt {row['ID']}")

    finally:
        unload_selected_model(model, tokenizer)

results_df = pd.DataFrame(all_results)

print("Total result rows:", len(results_df))
display(results_df.head())

Loading Microsoft Phi-3 Mini (microsoft/Phi-3-mini-4k-instruct)...

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.44k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/16.5k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

Loaded: microsoft/Phi-3-mini-4k-instruct
Microsoft Phi-3 Mini - completed prompt 1
Microsoft Phi-3 Mini - completed prompt 2
Microsoft Phi-3 Mini - completed prompt 3
Microsoft Phi-3 Mini - completed prompt 4
Microsoft Phi-3 Mini - completed prompt 5
Microsoft Phi-3 Mini - completed prompt 6
Microsoft Phi-3 Mini - completed prompt 7
Microsoft Phi-3 Mini - completed prompt 8
Microsoft Phi-3 Mini - completed prompt 9
Microsoft Phi-3 Mini - completed prompt 10
Microsoft Phi-3 Mini - completed prompt 11
Microsoft Phi-3 Mini - completed prompt 12
Microsoft Phi-3 Mini - completed prompt 13
Microsoft Phi-3 Mini - completed prompt 14
Microsoft Phi-3 Mini - completed prompt 15
Microsoft Phi-3 Mini - completed prompt 16
Microsoft Phi-3 Mini - completed prompt 17
Microsoft Phi-3 Mini - completed prompt 18
Microsoft Phi-3 Mini - completed prompt 19
Microsoft Phi-3 Mini - completed prompt 20
Microsoft Phi-3 Mini - completed prompt 21
Microsoft Phi-3 Mini - completed prompt 22
Microsoft Phi-3 Mini - completed prompt 23
Microsoft Phi-3 Mini - completed prompt 24
Microsoft Phi-3 Mini - completed prompt 25
Microsoft Phi-3 Mini - completed prompt 26
Microsoft Phi-3 Mini - completed prompt 27
Microsoft Phi-3 Mini - completed prompt 28
Microsoft Phi-3 Mini - completed prompt 29
Microsoft Phi-3 Mini - completed prompt 30
Microsoft Phi-3 Mini - completed prompt 31
Microsoft Phi-3 Mini - completed prompt 32
Microsoft Phi-3 Mini - completed prompt 33
Microsoft Phi-3 Mini - completed prompt 34
Microsoft Phi-3 Mini - completed prompt 35
Microsoft Phi-3 Mini - completed prompt 36
Microsoft Phi-3 Mini - completed prompt 37
Microsoft Phi-3 Mini - completed prompt 38
Microsoft Phi-3 Mini - completed prompt 39
Microsoft Phi-3 Mini - completed prompt 40
Microsoft Phi-3 Mini - completed prompt 41
Microsoft Phi-3 Mini - completed prompt 42
Microsoft Phi-3 Mini - completed prompt 43
Microsoft Phi-3 Mini - completed prompt 44
Microsoft Phi-3 Mini - completed prompt 45
Microsoft Phi-3 Mini - completed prompt 46
Microsoft Phi-3 Mini - completed prompt 47
Microsoft Phi-3 Mini - completed prompt 48
Microsoft Phi-3 Mini - completed prompt 49
Microsoft Phi-3 Mini - completed prompt 50
Microsoft Phi-3 Mini - completed prompt 51
Microsoft Phi-3 Mini - completed prompt 52
Microsoft Phi-3 Mini - completed prompt 53
Microsoft Phi-3 Mini - completed prompt 54
Microsoft Phi-3 Mini - completed prompt 55
Microsoft Phi-3 Mini - completed prompt 56
Microsoft Phi-3 Mini - completed prompt 57
Microsoft Phi-3 Mini - completed prompt 58
Microsoft Phi-3 Mini - completed prompt 59
Microsoft Phi-3 Mini - completed prompt 60
Microsoft Phi-3 Mini - completed prompt 61
Microsoft Phi-3 Mini - completed prompt 62
Microsoft Phi-3 Mini - completed prompt 63
Microsoft Phi-3 Mini - completed prompt 64
Microsoft Phi-3 Mini - completed prompt 65
Microsoft Phi-3 Mini - completed prompt 66
Microsoft Phi-3 Mini - completed prompt 67
Microsoft Phi-3 Mini - completed prompt 68
Microsoft Phi-3 Mini - completed prompt 69
Microsoft Phi-3 Mini - completed prompt 70
Microsoft Phi-3 Mini - completed prompt 71
Microsoft Phi-3 Mini - completed prompt 72
Microsoft Phi-3 Mini - completed prompt 73
Microsoft Phi-3 Mini - completed prompt 74
Microsoft Phi-3 Mini - completed prompt 75
Microsoft Phi-3 Mini - completed prompt 76
Microsoft Phi-3 Mini - completed prompt 77
Microsoft Phi-3 Mini - completed prompt 78
Microsoft Phi-3 Mini - completed prompt 79
Microsoft Phi-3 Mini - completed prompt 80
Microsoft Phi-3 Mini - completed prompt 81
Microsoft Phi-3 Mini - completed prompt 82
Microsoft Phi-3 Mini - completed prompt 83
Microsoft Phi-3 Mini - completed prompt 84
Microsoft Phi-3 Mini - completed prompt 85
Microsoft Phi-3 Mini - completed prompt 86
Microsoft Phi-3 Mini - completed prompt 87
Microsoft Phi-3 Mini - completed prompt 88
Microsoft Phi-3 Mini - completed prompt 89
Microsoft Phi-3 Mini - completed prompt 90
Microsoft Phi-3 Mini - completed prompt 91
Microsoft Phi-3 Mini - completed prompt 92
Microsoft Phi-3 Mini - completed prompt 93
Microsoft Phi-3 Mini - completed prompt 94
Microsoft Phi-3 Mini - completed prompt 95
Microsoft Phi-3 Mini - completed prompt 96
Microsoft Phi-3 Mini - completed prompt 97
Microsoft Phi-3 Mini - completed prompt 98
Microsoft Phi-3 Mini - completed prompt 99
Microsoft Phi-3 Mini - completed prompt 100

Loading Google Gemma-2-2B-IT (google/gemma-2-2b-it)...

config.json:   0%|          | 0.00/838 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/47.0k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/288 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

Loaded: google/gemma-2-2b-it
Google Gemma-2-2B-IT - completed prompt 1
Google Gemma-2-2B-IT - completed prompt 2
Google Gemma-2-2B-IT - completed prompt 3
Google Gemma-2-2B-IT - completed prompt 4
Google Gemma-2-2B-IT - completed prompt 5
Google Gemma-2-2B-IT - completed prompt 6
Google Gemma-2-2B-IT - completed prompt 7
Google Gemma-2-2B-IT - completed prompt 8
Google Gemma-2-2B-IT - completed prompt 9
Google Gemma-2-2B-IT - completed prompt 10
Google Gemma-2-2B-IT - completed prompt 11
Google Gemma-2-2B-IT - completed prompt 12
Google Gemma-2-2B-IT - completed prompt 13
Google Gemma-2-2B-IT - completed prompt 14
Google Gemma-2-2B-IT - completed prompt 15
Google Gemma-2-2B-IT - completed prompt 16
Google Gemma-2-2B-IT - completed prompt 17
Google Gemma-2-2B-IT - completed prompt 18
Google Gemma-2-2B-IT - completed prompt 19
Google Gemma-2-2B-IT - completed prompt 20
Google Gemma-2-2B-IT - completed prompt 21
Google Gemma-2-2B-IT - completed prompt 22
Google Gemma-2-2B-IT - completed prompt 23
Google Gemma-2-2B-IT - completed prompt 24
Google Gemma-2-2B-IT - completed prompt 25
Google Gemma-2-2B-IT - completed prompt 26
Google Gemma-2-2B-IT - completed prompt 27
Google Gemma-2-2B-IT - completed prompt 28
Google Gemma-2-2B-IT - completed prompt 29
Google Gemma-2-2B-IT - completed prompt 30
Google Gemma-2-2B-IT - completed prompt 31
Google Gemma-2-2B-IT - completed prompt 32
Google Gemma-2-2B-IT - completed prompt 33
Google Gemma-2-2B-IT - completed prompt 34
Google Gemma-2-2B-IT - completed prompt 35
Google Gemma-2-2B-IT - completed prompt 36
Google Gemma-2-2B-IT - completed prompt 37
Google Gemma-2-2B-IT - completed prompt 38
Google Gemma-2-2B-IT - completed prompt 39
Google Gemma-2-2B-IT - completed prompt 40
Google Gemma-2-2B-IT - completed prompt 41
Google Gemma-2-2B-IT - completed prompt 42
Google Gemma-2-2B-IT - completed prompt 43
Google Gemma-2-2B-IT - completed prompt 44
Google Gemma-2-2B-IT - completed prompt 45
Google Gemma-2-2B-IT - completed prompt 46
Google Gemma-2-2B-IT - completed prompt 47
Google Gemma-2-2B-IT - completed prompt 48
Google Gemma-2-2B-IT - completed prompt 49
Google Gemma-2-2B-IT - completed prompt 50
Google Gemma-2-2B-IT - completed prompt 51
Google Gemma-2-2B-IT - completed prompt 52
Google Gemma-2-2B-IT - completed prompt 53
Google Gemma-2-2B-IT - completed prompt 54
Google Gemma-2-2B-IT - completed prompt 55
Google Gemma-2-2B-IT - completed prompt 56
Google Gemma-2-2B-IT - completed prompt 57
Google Gemma-2-2B-IT - completed prompt 58
Google Gemma-2-2B-IT - completed prompt 59
Google Gemma-2-2B-IT - completed prompt 60
Google Gemma-2-2B-IT - completed prompt 61
Google Gemma-2-2B-IT - completed prompt 62
Google Gemma-2-2B-IT - completed prompt 63
Google Gemma-2-2B-IT - completed prompt 64
Google Gemma-2-2B-IT - completed prompt 65
Google Gemma-2-2B-IT - completed prompt 66
Google Gemma-2-2B-IT - completed prompt 67
Google Gemma-2-2B-IT - completed prompt 68
Google Gemma-2-2B-IT - completed prompt 69
Google Gemma-2-2B-IT - completed prompt 70
Google Gemma-2-2B-IT - completed prompt 71
Google Gemma-2-2B-IT - completed prompt 72
Google Gemma-2-2B-IT - completed prompt 73
Google Gemma-2-2B-IT - completed prompt 74
Google Gemma-2-2B-IT - completed prompt 75
Google Gemma-2-2B-IT - completed prompt 76
Google Gemma-2-2B-IT - completed prompt 77
Google Gemma-2-2B-IT - completed prompt 78
Google Gemma-2-2B-IT - completed prompt 79
Google Gemma-2-2B-IT - completed prompt 80
Google Gemma-2-2B-IT - completed prompt 81
Google Gemma-2-2B-IT - completed prompt 82
Google Gemma-2-2B-IT - completed prompt 83
Google Gemma-2-2B-IT - completed prompt 84
Google Gemma-2-2B-IT - completed prompt 85
Google Gemma-2-2B-IT - completed prompt 86
Google Gemma-2-2B-IT - completed prompt 87
Google Gemma-2-2B-IT - completed prompt 88
Google Gemma-2-2B-IT - completed prompt 89
Google Gemma-2-2B-IT - completed prompt 90
Google Gemma-2-2B-IT - completed prompt 91
Google Gemma-2-2B-IT - completed prompt 92
Google Gemma-2-2B-IT - completed prompt 93
Google Gemma-2-2B-IT - completed prompt 94
Google Gemma-2-2B-IT - completed prompt 95
Google Gemma-2-2B-IT - completed prompt 96
Google Gemma-2-2B-IT - completed prompt 97
Google Gemma-2-2B-IT - completed prompt 98
Google Gemma-2-2B-IT - completed prompt 99
Google Gemma-2-2B-IT - completed prompt 100

Loading Mistral-7B-Instruct-v0.3 (mistralai/Mistral-7B-Instruct-v0.3)...

config.json:   0%|          | 0.00/601 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/141k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/587k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Loaded: mistralai/Mistral-7B-Instruct-v0.3
Mistral-7B-Instruct-v0.3 - completed prompt 1
Mistral-7B-Instruct-v0.3 - completed prompt 2
Mistral-7B-Instruct-v0.3 - completed prompt 3
Mistral-7B-Instruct-v0.3 - completed prompt 4
Mistral-7B-Instruct-v0.3 - completed prompt 5
Mistral-7B-Instruct-v0.3 - completed prompt 6
Mistral-7B-Instruct-v0.3 - completed prompt 7
Mistral-7B-Instruct-v0.3 - completed prompt 8
Mistral-7B-Instruct-v0.3 - completed prompt 9
Mistral-7B-Instruct-v0.3 - completed prompt 10
Mistral-7B-Instruct-v0.3 - completed prompt 11
Mistral-7B-Instruct-v0.3 - completed prompt 12
Mistral-7B-Instruct-v0.3 - completed prompt 13
Mistral-7B-Instruct-v0.3 - completed prompt 14
Mistral-7B-Instruct-v0.3 - completed prompt 15
Mistral-7B-Instruct-v0.3 - completed prompt 16
Mistral-7B-Instruct-v0.3 - completed prompt 17
Mistral-7B-Instruct-v0.3 - completed prompt 18
Mistral-7B-Instruct-v0.3 - completed prompt 19
Mistral-7B-Instruct-v0.3 - completed prompt 20
Mistral-7B-Instruct-v0.3 - completed prompt 21
Mistral-7B-Instruct-v0.3 - completed prompt 22
Mistral-7B-Instruct-v0.3 - completed prompt 23
Mistral-7B-Instruct-v0.3 - completed prompt 24
Mistral-7B-Instruct-v0.3 - completed prompt 25
Mistral-7B-Instruct-v0.3 - completed prompt 26
Mistral-7B-Instruct-v0.3 - completed prompt 27
Mistral-7B-Instruct-v0.3 - completed prompt 28
Mistral-7B-Instruct-v0.3 - completed prompt 29
Mistral-7B-Instruct-v0.3 - completed prompt 30
Mistral-7B-Instruct-v0.3 - completed prompt 31
Mistral-7B-Instruct-v0.3 - completed prompt 32
Mistral-7B-Instruct-v0.3 - completed prompt 33
Mistral-7B-Instruct-v0.3 - completed prompt 34
Mistral-7B-Instruct-v0.3 - completed prompt 35
Mistral-7B-Instruct-v0.3 - completed prompt 36
Mistral-7B-Instruct-v0.3 - completed prompt 37
Mistral-7B-Instruct-v0.3 - completed prompt 38
Mistral-7B-Instruct-v0.3 - completed prompt 39
Mistral-7B-Instruct-v0.3 - completed prompt 40
Mistral-7B-Instruct-v0.3 - completed prompt 41
Mistral-7B-Instruct-v0.3 - completed prompt 42
Mistral-7B-Instruct-v0.3 - completed prompt 43
Mistral-7B-Instruct-v0.3 - completed prompt 44
Mistral-7B-Instruct-v0.3 - completed prompt 45
Mistral-7B-Instruct-v0.3 - completed prompt 46
Mistral-7B-Instruct-v0.3 - completed prompt 47
Mistral-7B-Instruct-v0.3 - completed prompt 48
Mistral-7B-Instruct-v0.3 - completed prompt 49
Mistral-7B-Instruct-v0.3 - completed prompt 50
Mistral-7B-Instruct-v0.3 - completed prompt 51
Mistral-7B-Instruct-v0.3 - completed prompt 52
Mistral-7B-Instruct-v0.3 - completed prompt 53
Mistral-7B-Instruct-v0.3 - completed prompt 54
Mistral-7B-Instruct-v0.3 - completed prompt 55
Mistral-7B-Instruct-v0.3 - completed prompt 56
Mistral-7B-Instruct-v0.3 - completed prompt 57
Mistral-7B-Instruct-v0.3 - completed prompt 58
Mistral-7B-Instruct-v0.3 - completed prompt 59
Mistral-7B-Instruct-v0.3 - completed prompt 60
Mistral-7B-Instruct-v0.3 - completed prompt 61
Mistral-7B-Instruct-v0.3 - completed prompt 62
Mistral-7B-Instruct-v0.3 - completed prompt 63
Mistral-7B-Instruct-v0.3 - completed prompt 64
Mistral-7B-Instruct-v0.3 - completed prompt 65
Mistral-7B-Instruct-v0.3 - completed prompt 66
Mistral-7B-Instruct-v0.3 - completed prompt 67
Mistral-7B-Instruct-v0.3 - completed prompt 68
Mistral-7B-Instruct-v0.3 - completed prompt 69
Mistral-7B-Instruct-v0.3 - completed prompt 70
Mistral-7B-Instruct-v0.3 - completed prompt 71
Mistral-7B-Instruct-v0.3 - completed prompt 72
Mistral-7B-Instruct-v0.3 - completed prompt 73
Mistral-7B-Instruct-v0.3 - completed prompt 74
Mistral-7B-Instruct-v0.3 - completed prompt 75
Mistral-7B-Instruct-v0.3 - completed prompt 76
Mistral-7B-Instruct-v0.3 - completed prompt 77
Mistral-7B-Instruct-v0.3 - completed prompt 78
Mistral-7B-Instruct-v0.3 - completed prompt 79
Mistral-7B-Instruct-v0.3 - completed prompt 80
Mistral-7B-Instruct-v0.3 - completed prompt 81
Mistral-7B-Instruct-v0.3 - completed prompt 82
Mistral-7B-Instruct-v0.3 - completed prompt 83
Mistral-7B-Instruct-v0.3 - completed prompt 84
Mistral-7B-Instruct-v0.3 - completed prompt 85
Mistral-7B-Instruct-v0.3 - completed prompt 86
Mistral-7B-Instruct-v0.3 - completed prompt 87
Mistral-7B-Instruct-v0.3 - completed prompt 88
Mistral-7B-Instruct-v0.3 - completed prompt 89
Mistral-7B-Instruct-v0.3 - completed prompt 90
Mistral-7B-Instruct-v0.3 - completed prompt 91
Mistral-7B-Instruct-v0.3 - completed prompt 92
Mistral-7B-Instruct-v0.3 - completed prompt 93
Mistral-7B-Instruct-v0.3 - completed prompt 94
Mistral-7B-Instruct-v0.3 - completed prompt 95
Mistral-7B-Instruct-v0.3 - completed prompt 96
Mistral-7B-Instruct-v0.3 - completed prompt 97
Mistral-7B-Instruct-v0.3 - completed prompt 98
Mistral-7B-Instruct-v0.3 - completed prompt 99
Mistral-7B-Instruct-v0.3 - completed prompt 100

Loading Qwen2.5-7B-Instruct (Qwen/Qwen2.5-7B-Instruct)...

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Loaded: Qwen/Qwen2.5-7B-Instruct
Qwen2.5-7B-Instruct - completed prompt 1
Qwen2.5-7B-Instruct - completed prompt 2
Qwen2.5-7B-Instruct - completed prompt 3
Qwen2.5-7B-Instruct - completed prompt 4
Qwen2.5-7B-Instruct - completed prompt 5
Qwen2.5-7B-Instruct - completed prompt 6
Qwen2.5-7B-Instruct - completed prompt 7
Qwen2.5-7B-Instruct - completed prompt 8
Qwen2.5-7B-Instruct - completed prompt 9
Qwen2.5-7B-Instruct - completed prompt 10
Qwen2.5-7B-Instruct - completed prompt 11
Qwen2.5-7B-Instruct - completed prompt 12
Qwen2.5-7B-Instruct - completed prompt 13
Qwen2.5-7B-Instruct - completed prompt 14
Qwen2.5-7B-Instruct - completed prompt 15
Qwen2.5-7B-Instruct - completed prompt 16
Qwen2.5-7B-Instruct - completed prompt 17
Qwen2.5-7B-Instruct - completed prompt 18
Qwen2.5-7B-Instruct - completed prompt 19
Qwen2.5-7B-Instruct - completed prompt 20
Qwen2.5-7B-Instruct - completed prompt 21
Qwen2.5-7B-Instruct - completed prompt 22
Qwen2.5-7B-Instruct - completed prompt 23
Qwen2.5-7B-Instruct - completed prompt 24
Qwen2.5-7B-Instruct - completed prompt 25
Qwen2.5-7B-Instruct - completed prompt 26
Qwen2.5-7B-Instruct - completed prompt 27
Qwen2.5-7B-Instruct - completed prompt 28
Qwen2.5-7B-Instruct - completed prompt 29
Qwen2.5-7B-Instruct - completed prompt 30
Qwen2.5-7B-Instruct - completed prompt 31
Qwen2.5-7B-Instruct - completed prompt 32
Qwen2.5-7B-Instruct - completed prompt 33
Qwen2.5-7B-Instruct - completed prompt 34
Qwen2.5-7B-Instruct - completed prompt 35
Qwen2.5-7B-Instruct - completed prompt 36
Qwen2.5-7B-Instruct - completed prompt 37
Qwen2.5-7B-Instruct - completed prompt 38
Qwen2.5-7B-Instruct - completed prompt 39
Qwen2.5-7B-Instruct - completed prompt 40
Qwen2.5-7B-Instruct - completed prompt 41
Qwen2.5-7B-Instruct - completed prompt 42
Qwen2.5-7B-Instruct - completed prompt 43
Qwen2.5-7B-Instruct - completed prompt 44
Qwen2.5-7B-Instruct - completed prompt 45
Qwen2.5-7B-Instruct - completed prompt 46
Qwen2.5-7B-Instruct - completed prompt 47
Qwen2.5-7B-Instruct - completed prompt 48
Qwen2.5-7B-Instruct - completed prompt 49
Qwen2.5-7B-Instruct - completed prompt 50
Qwen2.5-7B-Instruct - completed prompt 51
Qwen2.5-7B-Instruct - completed prompt 52
Qwen2.5-7B-Instruct - completed prompt 53
Qwen2.5-7B-Instruct - completed prompt 54
Qwen2.5-7B-Instruct - completed prompt 55
Qwen2.5-7B-Instruct - completed prompt 56
Qwen2.5-7B-Instruct - completed prompt 57
Qwen2.5-7B-Instruct - completed prompt 58
Qwen2.5-7B-Instruct - completed prompt 59
Qwen2.5-7B-Instruct - completed prompt 60
Qwen2.5-7B-Instruct - completed prompt 61
Qwen2.5-7B-Instruct - completed prompt 62
Qwen2.5-7B-Instruct - completed prompt 63
Qwen2.5-7B-Instruct - completed prompt 64
Qwen2.5-7B-Instruct - completed prompt 65
Qwen2.5-7B-Instruct - completed prompt 66
Qwen2.5-7B-Instruct - completed prompt 67
Qwen2.5-7B-Instruct - completed prompt 68
Qwen2.5-7B-Instruct - completed prompt 69
Qwen2.5-7B-Instruct - completed prompt 70
Qwen2.5-7B-Instruct - completed prompt 71
Qwen2.5-7B-Instruct - completed prompt 72
Qwen2.5-7B-Instruct - completed prompt 73
Qwen2.5-7B-Instruct - completed prompt 74
Qwen2.5-7B-Instruct - completed prompt 75
Qwen2.5-7B-Instruct - completed prompt 76
Qwen2.5-7B-Instruct - completed prompt 77
Qwen2.5-7B-Instruct - completed prompt 78
Qwen2.5-7B-Instruct - completed prompt 79
Qwen2.5-7B-Instruct - completed prompt 80
Qwen2.5-7B-Instruct - completed prompt 81
Qwen2.5-7B-Instruct - completed prompt 82
Qwen2.5-7B-Instruct - completed prompt 83
Qwen2.5-7B-Instruct - completed prompt 84
Qwen2.5-7B-Instruct - completed prompt 85
Qwen2.5-7B-Instruct - completed prompt 86
Qwen2.5-7B-Instruct - completed prompt 87
Qwen2.5-7B-Instruct - completed prompt 88
Qwen2.5-7B-Instruct - completed prompt 89
Qwen2.5-7B-Instruct - completed prompt 90
Qwen2.5-7B-Instruct - completed prompt 91
Qwen2.5-7B-Instruct - completed prompt 92
Qwen2.5-7B-Instruct - completed prompt 93
Qwen2.5-7B-Instruct - completed prompt 94
Qwen2.5-7B-Instruct - completed prompt 95
Qwen2.5-7B-Instruct - completed prompt 96
Qwen2.5-7B-Instruct - completed prompt 97
Qwen2.5-7B-Instruct - completed prompt 98
Qwen2.5-7B-Instruct - completed prompt 99
Qwen2.5-7B-Instruct - completed prompt 100
Total result rows: 400

,Model Label,Model ID,Model Size,Developer,ID,Category,Difficulty,Prompt,Reference Answer,Response,Latency,Generated Tokens,Response Length,Tokens/sec,GPU Peak Memory GB,CPU Process Memory GB
0,Microsoft Phi-3 Mini,microsoft/Phi-3-mini-4k-instruct,3.8B,Microsoft,1,Account Management,Easy,I forgot my password. How can I reset it?,"Click the ""Forgot Password"" option on the logi...","To reset your password, please follow these st...",6.566848,137,101,20.862367,7.233950,2.889015
1,Microsoft Phi-3 Mini,microsoft/Phi-3-mini-4k-instruct,3.8B,Microsoft,2,Account Management,Easy,I can't log into my account.,Verify your email and password are correct. If...,I'm sorry to hear that you're having trouble l...,1.704478,44,34,25.814349,7.157774,2.889126
2,Microsoft Phi-3 Mini,microsoft/Phi-3-mini-4k-instruct,3.8B,Microsoft,3,Account Management,Easy,My account is locked. What should I do?,Wait for the lock period to expire or contact ...,I'm sorry to hear that your account is locked....,5.363248,140,102,26.103586,7.233950,2.889980
3,Microsoft Phi-3 Mini,microsoft/Phi-3-mini-4k-instruct,3.8B,Microsoft,4,Account Management,Easy,How do I change my email address?,"Go to your account settings, update your email...","To change your email address, please follow th...",5.777017,150,106,25.964956,7.233950,2.890125
4,Microsoft Phi-3 Mini,microsoft/Phi-3-mini-4k-instruct,3.8B,Microsoft,5,Account Management,Medium,"I changed my email yesterday, and now I can't ...",Try logging in with your new email address. If...,I'm sorry to hear that you're having trouble s...,3.004772,77,56,25.625907,7.172503,2.899868

## BERTScore for All Model Outputs

In [11]:
from bert_score import score

candidate_responses = results_df["Response"].tolist()
reference_answers = results_df["Reference Answer"].tolist()

bert_device = "cuda" if torch.cuda.is_available() else "cpu"

try:
    P, R, F1 = score(
        candidate_responses,
        reference_answers,
        lang="en",
        verbose=True,
        batch_size=8,
        device=bert_device
    )
except RuntimeError as error:
    if bert_device == "cuda" and "out of memory" in str(error).lower():
        print("BERTScore ran out of GPU memory. Retrying on CPU...")
        torch.cuda.empty_cache()
        gc.collect()
        P, R, F1 = score(
            candidate_responses,
            reference_answers,
            lang="en",
            verbose=True,
            batch_size=4,
            device="cpu"
        )
    else:
        raise

results_df["BERTScore Precision"] = P.cpu().numpy()
results_df["BERTScore Recall"] = R.cpu().numpy()
results_df["BERTScore F1"] = F1.cpu().numpy()

print("Mean BERTScore F1:", results_df["BERTScore F1"].mean())

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

calculating scores...
computing bert embedding.

  0%|          | 0/63 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/50 [00:00<?, ?it/s]

done in 2.75 seconds, 145.32 sentences/sec
Mean BERTScore F1: 0.86332834

## ROUGE Scores

In [12]:
from rouge_score import rouge_scorer

rouge = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"],
    use_stemmer=True
)

def calculate_rouge(reference, response):
    scores = rouge.score(str(reference), str(response))
    return pd.Series({
        "ROUGE-1": scores["rouge1"].fmeasure,
        "ROUGE-2": scores["rouge2"].fmeasure,
        "ROUGE-L": scores["rougeL"].fmeasure
    })

rouge_df = results_df.apply(
    lambda row: calculate_rouge(row["Reference Answer"], row["Response"]),
    axis=1
)

results_df = pd.concat([results_df, rouge_df], axis=1)

print("Mean ROUGE-L:", results_df["ROUGE-L"].mean())

Mean ROUGE-L: 0.17155102059143446

## BLEU Scores

In [13]:
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

smooth = SmoothingFunction().method1

def calculate_bleu(reference, response):
    return sentence_bleu(
        [str(reference).split()],
        str(response).split(),
        smoothing_function=smooth
    )

results_df["BLEU"] = results_df.apply(
    lambda row: calculate_bleu(row["Reference Answer"], row["Response"]),
    axis=1
)

print("Mean BLEU:", results_df["BLEU"].mean())

Mean BLEU: 0.017695874850572932

## Inference Cost Score

This is a custom score, not money cost. It combines latency and peak GPU memory.

In [14]:
results_df["Inference Cost Score"] = (
    results_df["Latency"] * results_df["GPU Peak Memory GB"]
)

## Clean Summary Table by Model

In [15]:
summary_df = (
    results_df
    .groupby(["Model Label", "Model ID", "Model Size", "Developer"], as_index=False)
    .agg(
        Prompts=("ID", "count"),
        Mean_Latency=("Latency", "mean"),
        Mean_Generated_Tokens=("Generated Tokens", "mean"),
        Mean_Response_Length=("Response Length", "mean"),
        Mean_Tokens_per_Second=("Tokens/sec", "mean"),
        Mean_GPU_Peak_Memory_GB=("GPU Peak Memory GB", "mean"),
        Mean_CPU_Process_Memory_GB=("CPU Process Memory GB", "mean"),
        Mean_BERTScore_F1=("BERTScore F1", "mean"),
        Mean_ROUGE_1=("ROUGE-1", "mean"),
        Mean_ROUGE_2=("ROUGE-2", "mean"),
        Mean_ROUGE_L=("ROUGE-L", "mean"),
        Mean_BLEU=("BLEU", "mean"),
        Mean_Inference_Cost_Score=("Inference Cost Score", "mean")
    )
    .sort_values("Mean_BERTScore_F1", ascending=False)
)

display(
    summary_df.style
    .format({
        "Mean_Latency": "{:.3f}",
        "Mean_Generated_Tokens": "{:.1f}",
        "Mean_Response_Length": "{:.1f}",
        "Mean_Tokens_per_Second": "{:.2f}",
        "Mean_GPU_Peak_Memory_GB": "{:.2f}",
        "Mean_CPU_Process_Memory_GB": "{:.2f}",
        "Mean_BERTScore_F1": "{:.4f}",
        "Mean_ROUGE_1": "{:.4f}",
        "Mean_ROUGE_2": "{:.4f}",
        "Mean_ROUGE_L": "{:.4f}",
        "Mean_BLEU": "{:.4f}",
        "Mean_Inference_Cost_Score": "{:.4f}"
    })
    .hide(axis="index")
    .set_caption("Multi-Model Evaluation Summary")
)

## Optional Manual Evaluation Columns

In [16]:
results_df["Accuracy"] = ""
results_df["Relevance"] = ""
results_df["Completeness"] = ""
results_df["Helpfulness"] = ""

## Export Results

In [17]:
combined_results_path = "multi_model_customer_support_results.csv"
summary_path = "multi_model_metric_summary.csv"

results_df.to_csv(combined_results_path, index=False)
summary_df.to_csv(summary_path, index=False)

print("Saved:", combined_results_path)
print("Saved:", summary_path)

from google.colab import files
files.download(combined_results_path)
files.download(summary_path)

Saved: multi_model_customer_support_results.csv
Saved: multi_model_metric_summary.csv